name: ZPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get_secrets:
    runs-on: ubuntu-latest
    env:
      VENV: .venv
    steps:
      - uses: actions/checkout@v4

      - name: Create Python venv
        run: python3 -m venv $VENV

      - name: Setup Ansible and Deps
        run: |  
          $VENV/bin/python -m pip -U pip wheel
          $VENV/bin/pip install -r src/ansible/requirements.txt

      - name: Setup ZPA Collection
        run: | 
          $VENV/bin/ansible-galaxy collection install zscaler.zpacloud:==2.0.5

      - name: test ansible
        run: $VENV/bin/ansible-playbook --version